name: Java CI with Maven and Yarn

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: cd app && yarn install

    - name: Build application
      run: cd app && yarn build

    - name: Start application
      run: cd app && yarn start &

    - name: Run tests
      run: mvn test
